### PR TITLE
Add revert sam

### PR DESCRIPTION
**Pull request by murphycj2**
- I need to add this to the QC workflow to properly calculate mean target coverage in uncollapsed BAM.
- I tested is successfully on some example data.

### CODE REVIEW

**Comment by ionox0** [comment]
It looks good to me but, can you help me understand why the uncollapsed bam doesn't work, and what additional steps are needed to get proper coverage info?

**Comment by murphycj2** [comment]
@ionox0 thanks. It's because when CollectHsMetrics computes the average coverage over targets it only looks at deduplicated reads (but when it computes average coverage for bait regions it includes duplicate reads). Hence, the average target coverage calculation in the uncollapsed regions is not useful since this is duplex sequencing. So I need to run the RevertSam tool right before running CollectHsMetrics for uncollapsed bam

**Review by ionox0 — APPROVED** [review]

**Comment by murphycj2** [comment]
@ionox0 i agree, if we have no use of the mark duplicates flag, then we can probably remove it. I know marking reads as duplicates can be useful for calculating library size, so maybe that is why it was included. but since this is duplex sequencing on targeted regions, I don't see how that typical library size calculation can be useful versus just counting simplex/duplex families.

**Comment by rhshah** [comment]
> @ionox0 thanks. It's because when CollectHsMetrics computes the average coverage over targets it only looks at deduplicated reads (but when it computes average coverage for bait regions it includes duplicate reads). Hence, the average target coverage calculation in the uncollapsed regions is not useful since this is duplex sequencing. So I need to run the RevertSam tool to remove the duplication flag right before running CollectHsMetrics for uncollapsed bam

I am not sure if I understand this correctly, we are more concerned about coverage on target and that is being done correctly right?

**Pull request merged**
