### PR TITLE
Feature/hsmetrics

### PR DESCRIPTION
**Pull request by ionox0**

### CODE REVIEW

**Comment by rhshah** [comment]
@ionox0  @shalabhsuman  Can you also modify the `/docs/SUMMARY.md` file to point to the README.md for this tool

**Comment by rhshah** [comment]
#5

**Comment by ionox0** [comment]
@rhshah all set on these

btw, the hypen is removed from the docker hub URLs, so msk-access is actually mskaccess

`mskaccess/picard:0.6.1`

**Comment by rhshah** [comment]
> @rhshah all set on these
> 
> btw, the hypen is removed from the docker hub URLs, so msk-access is actually mskaccess
> 
> `mskaccess/picard:0.6.1`

Thanks that makes sense

**Pull request merged**
