### PR TITLE
Sequence qc CWL and docker

### PR DESCRIPTION
**Pull request by murphycj2**
- Docker and CWL for sequence_qc module

I tested it successfully with some example data.

Let me if the docker looks good then I can push to mskaccess docker repo

### CODE REVIEW

**Comment by ionox0** [comment]
Thanks Charlie, I'm going to be making a few updates to the module in the next 2 days, so I'll tag a new release and put in into pypi

There will be some new output files (HTML graphs using plotly) that come from this module, so once I finish that I can let you know and we should be able to just increment the version listed in the dockerfile

**Comment by ionox0** [comment]
Ok I've released 0.1.16 to pypi, so if you just update to that version I can probably merge this. 

One additional change is I renamed the `output_prefix` parameter to `sample_id` (sorry for the change, but thought this would make more sense / allow for it to show up as such in the plots).

The output files are named like this (note the html report that's included):
```
sample_id__noise.html

sample_id_noise_acgt.tsv
sample_id_noise_del.tsv
sample_id_noise_n.tsv

sample_id_noise_positions.tsv
sample_id_pileup.tsv
```

**Comment by murphycj2** [comment]
@ionox0 can you update sequence_qc's requirments.txt with required packages? I see cython and plotly are missing. otherwise I'll have to put the installation of those packages in the docker file

**Comment by murphycj2** [comment]
@ionox0 I just installed plotly for now. I built the docker and ran the cwl on some test data. it works and now outputs the html images.

**Comment by ionox0** [comment]
> @ionox0 I just installed plotly for now. I built the docker and ran the cwl on some test data. it works and now outputs the html images.

Sorry about that, I made a new release with plotly properly listed, but I'm ok with this solution too

**Pull request merged**
